### ISSUE TITLE
issue with sudo python3 setup.py install 

### ISSUE THREAD

**Issue by FrankensteinEvil0069** [epsylon/ufonet#306]
I wrote the command as it is but it is showing this output 
root@shreyas-kali-linux:~/ufonet-v1.6/ufonet# sudo python3 setup.py install

running install
running bdist_egg
running egg_info
creating ufonet.egg-info
writing ufonet.egg-info/PKG-INFO
writing dependency_links to ufonet.egg-info/dependency_links.txt
writing entry points to ufonet.egg-info/entry_points.txt
writing requirements to ufonet.egg-info/requires.txt
writing top-level names to ufonet.egg-info/top_level.txt
writing manifest file 'ufonet.egg-info/SOURCES.txt'
reading manifest file 'ufonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ufonet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/core
copying core/options.py -> build/lib/core
copying core/randomip.py -> build/lib/core
copying core/main.py -> build/lib/core
copying core/__init__.py -> build/lib/core
copying core/zombie.py -> build/lib/core
copying core/update.py -> build/lib/core
copying core/herd.py -> build/lib/core
copying core/ajaxmap.py -> build/lib/core
copying core/doll.py -> build/lib/core
copying core/webgui.py -> build/lib/core
creating build/lib/core/mods
copying core/mods/overlap.py -> build/lib/core/mods
copying core/mods/monlist.py -> build/lib/core/mods
copying core/mods/sniper.py -> build/lib/core/mods
copying core/mods/uforst.py -> build/lib/core/mods
copying core/mods/__init__.py -> build/lib/core/mods
copying core/mods/ufoudp.py -> build/lib/core/mods
copying core/mods/fraggle.py -> build/lib/core/mods
copying core/mods/loic.py -> build/lib/core/mods
copying core/mods/spray.py -> build/lib/core/mods
copying core/mods/ufoack.py -> build/lib/core/mods
copying core/mods/loris.py -> build/lib/core/mods
copying core/mods/pinger.py -> build/lib/core/mods
copying core/mods/droper.py -> build/lib/core/mods
copying core/mods/ufosyn.py -> build/lib/core/mods
copying core/mods/xmas.py -> build/lib/core/mods
copying core/mods/tachyon.py -> build/lib/core/mods
copying core/mods/nuke.py -> build/lib/core/mods
copying core/mods/smurf.py -> build/lib/core/mods
creating build/lib/core/tools
copying core/tools/grider.py -> build/lib/core/tools
copying core/tools/__init__.py -> build/lib/core/tools
copying core/tools/blackhole.py -> build/lib/core/tools
copying core/tools/abductor.py -> build/lib/core/tools
copying core/tools/crypter.py -> build/lib/core/tools
copying core/tools/inspector.py -> build/lib/core/tools
copying core/tools/ufoscan.py -> build/lib/core/tools
creating build/lib/core/js
copying core/js/ufo-cloud.css -> build/lib/core/js
copying core/js/style.css -> build/lib/core/js
copying core/js/ajaxmap.css -> build/lib/core/js
copying core/js/spaceinvaders.js -> build/lib/core/js
copying core/js/raphael.js -> build/lib/core/js
copying core/js/ufo.js -> build/lib/core/js
copying core/js/jquery-1.10.2.min.js -> build/lib/core/js
copying core/js/stars.js -> build/lib/core/js
copying core/js/rlayer-src.js -> build/lib/core/js
creating build/lib/core/js/leaflet
copying core/js/leaflet/leaflet.ie.css -> build/lib/core/js/leaflet
copying core/js/leaflet/leaflet.css -> build/lib/core/js/leaflet
copying core/js/leaflet/leaflet-src.js -> build/lib/core/js/leaflet
copying core/js/leaflet/leaflet.js -> build/lib/core/js/leaflet
creating build/lib/core/js/cluster
copying core/js/cluster/MarkerCluster.Default.ie.css -> build/lib/core/js/cluster
copying core/js/cluster/MarkerCluster.Default.css -> build/lib/core/js/cluster
copying core/js/cluster/leaflet.markercluster-src.js -> build/lib/core/js/cluster
copying core/js/cluster/leaflet.markercluster.js -> build/lib/core/js/cluster
copying core/js/cluster/MarkerCluster.css -> build/lib/core/js/cluster
creating build/lib/core/txt
copying core/txt/motherships.txt -> build/lib/core/txt
copying core/txt/misc.txt -> build/lib/core/txt
copying core/txt/wafs.txt -> build/lib/core/txt
copying core/txt/user-agents.txt -> build/lib/core/txt
creating build/lib/core/images
creating build/lib/core/images/crew
copying core/images/crew/link3.txt -> build/lib/core/images/crew
copying core/images/crew/link10.txt -> build/lib/core/images/crew
copying core/images/crew/link11.txt -> build/lib/core/images/crew
copying core/images/crew/link4.txt -> build/lib/core/images/crew
copying core/images/crew/link5.txt -> build/lib/core/images/crew
copying core/images/crew/link8.txt -> build/lib/core/images/crew
copying core/images/crew/link6.txt -> build/lib/core/images/crew
copying core/images/crew/link2.txt -> build/lib/core/images/crew
copying core/images/crew/link12.txt -> build/lib/core/images/crew
copying core/images/crew/link9.txt -> build/lib/core/images/crew
copying core/images/crew/link1.txt -> build/lib/core/images/crew
copying core/images/crew/link7.txt -> build/lib/core/images/crew
creating build/lib/core/images/aliens
copying core/images/aliens/alien11.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien2.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien12.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien13.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien7.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien9.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien5.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien10.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien1.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien8.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien3.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien6.txt -> build/lib/core/images/aliens
copying core/images/aliens/alien4.txt -> build/lib/core/images/aliens
copying core/images/aliens.txt -> build/lib/core/images
copying core/images/ufonet-logo.txt -> build/lib/core/images
copying core/images/mothership.txt -> build/lib/core/images
copying core/images/board.txt -> build/lib/core/images
copying core/images/favicon.txt -> build/lib/core/images
copying core/images/commander.txt -> build/lib/core/images
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/core
copying build/lib/core/options.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/overlap.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/monlist.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/sniper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/uforst.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/__init__.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoudp.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/fraggle.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loic.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/spray.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoack.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loris.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/pinger.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/droper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufosyn.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/xmas.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/tachyon.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/nuke.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/smurf.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/randomip.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/main.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/__init__.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/zombie.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/update.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/motherships.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/misc.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/wafs.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/user-agents.txt -> build/bdist.linux-x86_64/egg/core/txt
creating build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link3.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link10.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link11.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link4.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link5.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link8.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link6.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link2.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link12.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link9.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link1.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link7.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/aliens.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/ufonet-logo.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/mothership.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/board.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/favicon.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/commander.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien11.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien2.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien12.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien13.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien7.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien9.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien5.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien10.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien1.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien8.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien3.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien6.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien4.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/herd.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/grider.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/__init__.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/blackhole.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/abductor.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/crypter.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/inspector.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/ufoscan.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/ajaxmap.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo-cloud.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/spaceinvaders.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.ie.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster-src.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/raphael.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.ie.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet-src.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/style.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ajaxmap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jquery-1.10.2.min.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/stars.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/rlayer-src.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/doll.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/webgui.py -> build/bdist.linux-x86_64/egg/core
byte-compiling build/bdist.linux-x86_64/egg/core/options.py to options.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/overlap.py to overlap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/monlist.py to monlist.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/sniper.py to sniper.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/uforst.py to uforst.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoudp.py to ufoudp.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/fraggle.py to fraggle.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loic.py to loic.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/spray.py to spray.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoack.py to ufoack.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loris.py to loris.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/pinger.py to pinger.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/droper.py to droper.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufosyn.py to ufosyn.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/xmas.py to xmas.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/tachyon.py to tachyon.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/nuke.py to nuke.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/smurf.py to smurf.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/randomip.py to randomip.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/main.py to main.cpython-39.pyc
build/bdist.linux-x86_64/egg/core/main.py:3325: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if url_link not in zombies and url_link+os.linesep not in zombies_found and url_link is not "": # AI mode (parsing search engines mixed pool and stored army)
byte-compiling build/bdist.linux-x86_64/egg/core/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/zombie.py to zombie.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/update.py to update.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/herd.py to herd.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/grider.py to grider.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/blackhole.py to blackhole.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/abductor.py to abductor.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/crypter.py to crypter.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/inspector.py to inspector.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/ufoscan.py to ufoscan.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/ajaxmap.py to ajaxmap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/doll.py to doll.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/webgui.py to webgui.cpython-39.pyc
build/bdist.linux-x86_64/egg/core/webgui.py:2222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_target_dec is not "":
build/bdist.linux-x86_64/egg/core/webgui.py:2371: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 0: # not any data (or decryption allowed) on grid so discard
build/bdist.linux-x86_64/egg/core/webgui.py:2373: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 1: # add this player as a rookie
build/bdist.linux-x86_64/egg/core/webgui.py:2376: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 2: # add this player as a mercenary
build/bdist.linux-x86_64/egg/core/webgui.py:2379: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 3: # add this player as a bandit
build/bdist.linux-x86_64/egg/core/webgui.py:2382: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 4: # add this player as a ufommander
build/bdist.linux-x86_64/egg/core/webgui.py:2385: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 5: # add this player as a ufoleet
build/bdist.linux-x86_64/egg/core/webgui.py:4222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
build/bdist.linux-x86_64/egg/core/webgui.py:4249: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if key is not "":
build/bdist.linux-x86_64/egg/core/webgui.py:4328: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
build/bdist.linux-x86_64/egg/core/webgui.py:4390: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
build/bdist.linux-x86_64/egg/core/webgui.py:5501: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # stream creation + encryption + package send
build/bdist.linux-x86_64/egg/core/webgui.py:5712: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_enckey is not "": # stream creation + encryption + package send
build/bdist.linux-x86_64/egg/core/webgui.py:5778: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_enckey is not "": # stream creation + encryption + package send
build/bdist.linux-x86_64/egg/core/webgui.py:5842: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_enckey is not "": # stream creation + encryption + package send
build/bdist.linux-x86_64/egg/core/webgui.py:5913: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_enckey is not "": # stream creation + encryption + package send
build/bdist.linux-x86_64/egg/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
build/bdist.linux-x86_64/egg/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
build/bdist.linux-x86_64/egg/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
build/bdist.linux-x86_64/egg/core/webgui.py:6073: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if news_key is not "": # news decryption
build/bdist.linux-x86_64/egg/core/webgui.py:6095: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if missions_key is not "": # missions decryption
build/bdist.linux-x86_64/egg/core/webgui.py:6202: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "": # board decryption
build/bdist.linux-x86_64/egg/core/webgui.py:6281: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # grid decryption
build/bdist.linux-x86_64/egg/core/webgui.py:7033: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_deckey is not "": # wargames decryption
build/bdist.linux-x86_64/egg/core/webgui.py:7177: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_deckey is not "": # links decryption
build/bdist.linux-x86_64/egg/core/webgui.py:7227: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_deckey is not "": # streams decryption
build/bdist.linux-x86_64/egg/core/webgui.py:7279: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_deckey is not "": # globalnet decryption
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/ufonet-1.6-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ufonet-1.6-py3.9.egg
removing '/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg' (and everything under it)
creating /usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg
Extracting ufonet-1.6-py3.9.egg to /usr/local/lib/python3.9/dist-packages
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/main.py:3325: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if url_link not in zombies and url_link+os.linesep not in zombies_found and url_link is not "": # AI mode (parsing search engines mixed pool and stored army)
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_target_dec is not "":
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2371: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 0: # not any data (or decryption allowed) on grid so discard
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2373: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if v is 1: # add this player as a rookie
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2376: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 2: # add this player as a mercenary
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2379: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 3: # add this player as a bandit
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2382: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 4: # add this player as a ufommander
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:2385: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif v is 5: # add this player as a ufoleet
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:4222: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:4249: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if key is not "":
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:4328: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:4390: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if job_id is not "":
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:5501: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # stream creation + encryption + package send
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:5712: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_enckey is not "": # stream creation + encryption + package send
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:5778: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_enckey is not "": # stream creation + encryption + package send
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:5842: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_enckey is not "": # stream creation + encryption + package send
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:5913: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_enckey is not "": # stream creation + encryption + package send
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6003: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "" or board_topic is not "" or board_message is not "": # stream creation (topic | icon | nick | id | comment) + encryption (board_key) + package send (default blackhole)
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6073: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if news_key is not "": # news decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6095: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if missions_key is not "": # missions decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6202: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if board_key is not "": # board decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:6281: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if grid_key is not "": # grid decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:7033: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if wargames_deckey is not "": # wargames decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:7177: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if link_deckey is not "": # links decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:7227: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stream_deckey is not "": # streams decryption
/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg/core/webgui.py:7279: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if globalnet_deckey is not "": # globalnet decryption
ufonet 1.6 is already the active version in easy-install.pth
Installing ufonet script to /usr/local/bin
Installing ufonet script to /usr/local/bin

Installed /usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg
Processing dependencies for ufonet==1.6
Searching for GeoIP>=1.3.2
Reading https://pypi.org/simple/GeoIP/
Downloading https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz#sha256=a890da6a21574050692198f14b07aa4268a01371278dfc24f71cd9bc87ebf0e6
Best match: GeoIP 1.3.2
Processing GeoIP-1.3.2.tar.gz
Writing /tmp/easy_install-yipcvclc/GeoIP-1.3.2/setup.cfg
Running GeoIP-1.3.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yipcvclc/GeoIP-1.3.2/egg-dist-tmp-346p3w29
/usr/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
Warning: 'classifiers' should be a list, got type 'tuple'
warning: no files found matching 'ChangeLog'
py_GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory
   23 | #include "GeoIP.h"
      |          ^~~~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
PLEASE HELP

**Comment by epsylon** [comment]
@FrankensteinEvil0069 -> https://github.com/epsylon/ufonet/issues/301#issuecomment-792067529

A) You need to **--update** (or git clone again) your tool to have latest setup.py

B) https://ufonet.03c8.net/#installation 

`py_GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory`

1) sudo apt-get install libgeoip1 libgeoip-dev
2) sudo python3 setup.py install

**Comment by FrankensteinEvil0069** [comment]
> @FrankensteinEvil0069 -> [#301 (comment)](https://github.com/epsylon/ufonet/issues/301#issuecomment-792067529)
> 
> A) You need to **--update** (or git clone again) your tool to have latest setup.py
> 
> B) https://ufonet.03c8.net/#installation
> 
> `py_GeoIP.c:23:10: fatal error: GeoIP.h: No such file or directory`
> 
> 1. sudo apt-get install libgeoip1 libgeoip-dev
> 2. sudo python3 setup.py install

Thank You that helped 

root@shreyas-kali-linux:~/ufonet# python3 setup.py install
running install
running bdist_egg
running egg_info
writing ufonet.egg-info/PKG-INFO
writing dependency_links to ufonet.egg-info/dependency_links.txt
writing entry points to ufonet.egg-info/entry_points.txt
writing requirements to ufonet.egg-info/requires.txt
writing top-level names to ufonet.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'ufonet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/core
copying build/lib/core/options.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/overlap.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/monlist.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/sniper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/uforst.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/__init__.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoudp.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/fraggle.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loic.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/spray.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufoack.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/loris.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/pinger.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/droper.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/ufosyn.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/xmas.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/tachyon.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/nuke.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/mods/smurf.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib/core/randomip.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/main.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/__init__.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/zombie.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/update.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/motherships.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/misc.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/wafs.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib/core/txt/user-agents.txt -> build/bdist.linux-x86_64/egg/core/txt
creating build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link3.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link10.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link11.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link4.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link5.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link8.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link6.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link2.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link12.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link9.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link1.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/crew/link7.txt -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib/core/images/aliens.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/ufonet-logo.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/mothership.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/board.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/favicon.txt -> build/bdist.linux-x86_64/egg/core/images
copying build/lib/core/images/commander.txt -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien11.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien2.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien12.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien13.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien7.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien9.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien5.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien10.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien1.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien8.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien3.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien6.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/images/aliens/alien4.txt -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib/core/herd.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/grider.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/__init__.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/blackhole.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/abductor.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/crypter.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/inspector.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/tools/ufoscan.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib/core/ajaxmap.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo-cloud.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/spaceinvaders.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.ie.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.Default.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster-src.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/leaflet.markercluster.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/cluster/MarkerCluster.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib/core/js/raphael.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.ie.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet-src.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/leaflet/leaflet.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib/core/js/style.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ajaxmap.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/ufo.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/jquery-1.10.2.min.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/stars.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/js/rlayer-src.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib/core/doll.py -> build/bdist.linux-x86_64/egg/core
copying build/lib/core/webgui.py -> build/bdist.linux-x86_64/egg/core
byte-compiling build/bdist.linux-x86_64/egg/core/options.py to options.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/overlap.py to overlap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/monlist.py to monlist.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/sniper.py to sniper.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/uforst.py to uforst.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoudp.py to ufoudp.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/fraggle.py to fraggle.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loic.py to loic.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/spray.py to spray.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufoack.py to ufoack.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loris.py to loris.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/pinger.py to pinger.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/droper.py to droper.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufosyn.py to ufosyn.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/xmas.py to xmas.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/tachyon.py to tachyon.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/nuke.py to nuke.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/smurf.py to smurf.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/randomip.py to randomip.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/main.py to main.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/zombie.py to zombie.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/update.py to update.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/herd.py to herd.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/grider.py to grider.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/blackhole.py to blackhole.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/abductor.py to abductor.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/crypter.py to crypter.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/inspector.py to inspector.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/ufoscan.py to ufoscan.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/ajaxmap.py to ajaxmap.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/doll.py to doll.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/webgui.py to webgui.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ufonet-1.6-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ufonet-1.6-py3.9.egg
removing '/usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg' (and everything under it)
creating /usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg
Extracting ufonet-1.6-py3.9.egg to /usr/local/lib/python3.9/dist-packages
ufonet 1.6 is already the active version in easy-install.pth
Installing ufonet script to /usr/local/bin
Installing ufonet script to /usr/local/bin

Installed /usr/local/lib/python3.9/dist-packages/ufonet-1.6-py3.9.egg
Processing dependencies for ufonet==1.6
Searching for scapy-python3==0.26
Best match: scapy-python3 0.26
Processing scapy_python3-0.26-py3.9.egg
scapy-python3 0.26 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/scapy_python3-0.26-py3.9.egg
Searching for whois==0.9.8
Best match: whois 0.9.8
Processing whois-0.9.8-py3.9.egg
whois 0.9.8 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/whois-0.9.8-py3.9.egg
Searching for pycurl==7.43.0.6
Best match: pycurl 7.43.0.6
Adding pycurl 7.43.0.6 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
Adding pycrypto 2.6.1 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for requests==2.25.1
Best match: requests 2.25.1
Adding requests 2.25.1 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for pygeoip==0.3.2
Best match: pygeoip 0.3.2
Processing pygeoip-0.3.2-py3.9.egg
pygeoip 0.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/pygeoip-0.3.2-py3.9.egg
Searching for python-geoip==1.2
Best match: python-geoip 1.2
Processing python_geoip-1.2-py3.9.egg
python-geoip 1.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/python_geoip-1.2-py3.9.egg
Searching for GeoIP==1.3.2
Best match: GeoIP 1.3.2
Processing GeoIP-1.3.2-py3.9-linux-x86_64.egg
GeoIP 1.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/GeoIP-1.3.2-py3.9-linux-x86_64.egg
Searching for certifi==2020.6.20
Best match: certifi 2020.6.20
Adding certifi 2020.6.20 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for chardet==4.0.0
Best match: chardet 4.0.0
Adding chardet 4.0.0 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/lib/python3/dist-packages
Searching for urllib3==1.26.4
Best match: urllib3 1.26.4
Adding urllib3 1.26.4 to easy-install.pth file

Using /usr/local/lib/python3.9/dist-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for ufonet==1.6



BUT NOW I HAVE THIS PROBLEM 

root@shreyas-kali-linux:~/ufonet# python3 ufonet --download-zombies

Error importing: scapy lib. 

 To install it on Debian based systems:

 $ 'sudo apt-get install python3-scapy'

root@shreyas-kali-linux:~/ufonet# sudo apt-get install python3-scapy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-scapy is already the newest version (2.4.4-4).
0 upgraded, 0 newly installed, 0 to remove and 571 not upgraded.

**Comment by FrankensteinEvil0069** [comment]
BUT NOW I HAVE THIS PROBLEM

root@shreyas-kali-linux:~/ufonet# python3 ufonet --download-zombies

Error importing: scapy lib.

To install it on Debian based systems:

$ 'sudo apt-get install python3-scapy'

root@shreyas-kali-linux:~/ufonet# sudo apt-get install python3-scapy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-scapy is already the newest version (2.4.4-4).
0 upgraded, 0 newly installed, 0 to remove and 571 not upgraded.

**Comment by epsylon** [comment]
@FrankensteinEvil0069 "BUT NOW I HAVE THIS PROBLEM" <- This thread has been solved. Try to don't ask a new question on the same threads and multiple times (https://github.com/epsylon/ufonet/issues/274#issuecomment-805751066, https://github.com/epsylon/ufonet/issues/148#issuecomment-805753090 ). 

If you don't do it, you will be ignored. 

related -> https://github.com/epsylon/ufonet/issues/274#issuecomment-805761364

**Comment by FrankensteinEvil0069** [comment]
> @FrankensteinEvil0069 "BUT NOW I HAVE THIS PROBLEM" <- This thread has been solved. Try to don't ask a new question on the same threads and multiple times ([#274 (comment)](https://github.com/epsylon/ufonet/issues/274#issuecomment-805751066), [#148 (comment)](https://github.com/epsylon/ufonet/issues/148#issuecomment-805753090) ).
> 
> If you don't do it, you will be ignored.
> 
> related -> [#274 (comment)](https://github.com/epsylon/ufonet/issues/274#issuecomment-805761364)

Dear espylon, 
please check the latest reply at issue #274 
I'm still having the same issue
and I really dont know why ?

**Comment by epsylon** [comment]
@FrankensteinEvil0069 this thread is closed. Go to: https://github.com/epsylon/ufonet/issues/274#issuecomment-806483207

**Comment by ahmxd18** [comment]
Hey.... When I'm trying to install WifiPumpkin3 in Kali-Linux, it's showing me the following error:
warning: no files found matching 'CHANGELOG'
/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!


What do I do now?? The problem is appearing when I'm trying to install 'setup.py' from WifiPumpkin3 directory.
